-- SpotMap Database Schema - Complete initialization
-- Run this file to set up the database structure

-- Create database if not exists
CREATE DATABASE IF NOT EXISTS spotmap CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE spotmap;

-- ============================================
-- 1. USERS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY COMMENT 'UUID generated by app',
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(120) UNIQUE NOT NULL,
  password_hash VARCHAR(255),
  full_name VARCHAR(120),
  avatar_url VARCHAR(500),
  bio TEXT,
  role ENUM('user', 'moderator', 'admin') DEFAULT 'user',
  provider ENUM('local', 'google', 'facebook', 'instagram', 'twitter') DEFAULT 'local',
  provider_id VARCHAR(255),
  is_verified BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_login_at TIMESTAMP NULL,
  INDEX idx_email (email),
  INDEX idx_username (username),
  INDEX idx_role (role),
  INDEX idx_provider (provider)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 2. SPOTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS spots (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  latitude DECIMAL(10, 8) NOT NULL,
  longitude DECIMAL(11, 8) NOT NULL,
  category VARCHAR(50),
  tags JSON,
  image_url VARCHAR(500),
  image_path VARCHAR(500),
  status ENUM('pending', 'approved', 'rejected', 'hidden') DEFAULT 'approved',
  view_count INT DEFAULT 0,
  rating DECIMAL(3, 2) DEFAULT 0.00,
  rating_count INT DEFAULT 0,
  is_featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_id (user_id),
  INDEX idx_status (status),
  INDEX idx_category (category),
  INDEX idx_location (latitude, longitude),
  INDEX idx_rating (rating),
  SPATIAL INDEX idx_geom (POINT(latitude, longitude))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 3. RATINGS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS ratings (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  spot_id BIGINT NOT NULL,
  user_id CHAR(36) NOT NULL,
  rating TINYINT CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (spot_id) REFERENCES spots(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY unique_user_spot (user_id, spot_id),
  INDEX idx_spot_id (spot_id),
  INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 4. COMMENTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  spot_id BIGINT NOT NULL,
  user_id CHAR(36) NOT NULL,
  content TEXT NOT NULL,
  is_approved BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (spot_id) REFERENCES spots(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_spot_id (spot_id),
  INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 5. FAVORITES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  spot_id BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (spot_id) REFERENCES spots(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY unique_user_spot (user_id, spot_id),
  INDEX idx_user_id (user_id),
  INDEX idx_spot_id (spot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 6. REPORTS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  spot_id BIGINT NOT NULL,
  user_id CHAR(36) NOT NULL,
  reason VARCHAR(100),
  description TEXT,
  status ENUM('pending', 'reviewing', 'approved', 'rejected') DEFAULT 'pending',
  moderator_id CHAR(36),
  moderator_note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (spot_id) REFERENCES spots(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (moderator_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_status (status),
  INDEX idx_spot_id (spot_id),
  INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 7. ACTIVITY LOGS
-- ============================================
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id CHAR(36),
  action VARCHAR(50),
  resource_type VARCHAR(50),
  resource_id BIGINT,
  ip_address VARCHAR(45),
  user_agent TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_user_id (user_id),
  INDEX idx_action (action),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 8. MODERATION AUDIT LOG
-- ============================================
CREATE TABLE IF NOT EXISTS moderation_audit_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  moderator_id CHAR(36) NOT NULL COMMENT 'User performing moderation action',
  action VARCHAR(50) NOT NULL COMMENT 'Action: approve_spot, reject_spot, delete_comment, ban_user, etc.',
  target_type VARCHAR(50) NOT NULL COMMENT 'Resource type: spot, comment, user, report',
  target_id VARCHAR(100) NOT NULL COMMENT 'ID of the moderated resource',
  old_value TEXT COMMENT 'Previous state (JSON)',
  new_value TEXT COMMENT 'Updated state (JSON)',
  reason TEXT COMMENT 'Moderator justification for the action',
  metadata JSON COMMENT 'Additional context (IP, user_agent, referrer, etc.)',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (moderator_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_moderator_id (moderator_id),
  INDEX idx_action (action),
  INDEX idx_target (target_type, target_id),
  INDEX idx_created_at (created_at),
  INDEX idx_action_created (action, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Immutable audit trail for all moderation actions';

-- ============================================
-- 9. INSERT DEFAULT ADMIN USER
-- ============================================
INSERT IGNORE INTO users (id, username, email, password_hash, full_name, role, is_verified, is_active) VALUES
('550e8400-e29b-41d4-a716-446655440000', 'admin', 'admin@spotmap.local', '$2y$10$YIjlrBzijF0CRQfJlgOXaeQ5XlXvjnPBL6Oy5GS5TGRvXCDWTSAMG', 'Administrator', 'admin', TRUE, TRUE);

-- ============================================
-- 10. INSERT SAMPLE SPOTS
-- ============================================
INSERT INTO spots (user_id, title, description, latitude, longitude, category, tags, status) VALUES
-- Art & Street Art
('550e8400-e29b-41d4-a716-446655440000', 'Mural de Arte Callejero Centro', 'Impresionante mural de artista local con temática urbana', 40.4168, -3.7038, 'arte', '["arte", "callejero", "mural"]', 'approved'),
('550e8400-e29b-41d4-a716-446655440000', 'Galería Subterránea Vintage', 'Espacio artístico escondido con obras contemporáneas', 40.4200, -3.7000, 'arte', '["galería", "contemporáneo", "oculto"]', 'approved'),

-- Coffee & Food
('550e8400-e29b-41d4-a716-446655440000', 'Café del Artista', 'Pequeño café con ambiente acogedor y barista experto', 40.4150, -3.7050, 'café', '["café", "artesanal", "acogedor"]', 'approved'),
('550e8400-e29b-41d4-a716-446655440000', 'Tacos Auténticos del Centro', 'Puesto de tacos tradicionales con receta familiar', 40.4180, -3.7020, 'comida', '["tacos", "auténtico", "tradicional"]', 'approved'),
('550e8400-e29b-41d4-a716-446655440000', 'Pastelería Francesa Especial', 'Tienda de repostería con productos importados de Francia', 40.4160, -3.7080, 'café', '["pastelería", "francés", "gourmet"]', 'approved'),

-- Nature & Outdoors
('550e8400-e29b-41d4-a716-446655440000', 'Parque Secreto con Vistas', 'Pequeño parque elevado con vistas panorámicas de la ciudad', 40.4200, -3.6980, 'naturaleza', '["parque", "vistas", "secreto"]', 'approved'),
('550e8400-e29b-41d4-a716-446655440000', 'Jardín Botánico Oculto', 'Jardín tranquilo con plantas raras y diseño zen', 40.4140, -3.7100, 'naturaleza', '["jardín", "plantas", "tranquilo"]', 'approved'),

-- Music & Entertainment
('550e8400-e29b-41d4-a716-446655440000', 'Sala de Conciertos Indie', 'Venue intimo para música en vivo de artistas locales', 40.4190, -3.7030, 'música', '["música", "directo", "indie"]', 'approved'),
('550e8400-e29b-41d4-a716-446655440000', 'Karaoke Bar Retro', 'Bar nostálgico con éxitos de los 80-90 en alta definición', 40.4170, -3.7010, 'música', '["karaoke", "retro", "divertido"]', 'approved'),

-- Shopping & Markets
('550e8400-e29b-41d4-a716-446655440000', 'Mercadillo Vintage Semanal', 'Mercado de ropa y accesorios vintage los domingos', 40.4210, -3.6990, 'compras', '["vintage", "ropa", "mercado"]', 'approved'),
('550e8400-e29b-41d4-a716-446655440000', 'Tienda de Discos de Vinilo', 'Colección de vinilos clásicos y contemporáneos', 40.4155, -3.7025, 'compras', '["música", "vinilo", "colección"]', 'approved'),

-- Sports & Activities
('550e8400-e29b-41d4-a716-446655440000', 'Pista de Skate Pública', 'Skatepark con obstáculos para todos los niveles', 40.4175, -3.7015, 'deporte', '["skate", "acción", "público"]', 'approved'),
('550e8400-e29b-41d4-a716-446655440000', 'Cancha de Basket Callejera', 'Cancha urbana para partidas informales después del trabajo', 40.4185, -3.7035, 'deporte', '["basket", "urbano", "social"]', 'approved'),

-- Education & Culture
('550e8400-e29b-41d4-a716-446655440000', 'Biblioteca Comunitaria', 'Espacio libre para lectura, estudio y eventos comunitarios', 40.4195, -3.7005, 'educación', '["biblioteca", "estudio", "comunidad"]', 'approved'),
('550e8400-e29b-41d4-a716-446655440000', 'Taller de Fotografía Analógica', 'Clase práctica sobre fotografía en película y revelado', 40.4145, -3.7090, 'educación', '["fotografía", "analógico", "taller"]', 'approved');

-- ============================================
-- 11. CREATE INDEXES FOR PERFORMANCE
-- ============================================
CREATE INDEX idx_spots_category_status ON spots(category, status);
CREATE INDEX idx_spots_created_at ON spots(created_at);
CREATE INDEX idx_ratings_spot_created ON ratings(spot_id, created_at);
CREATE INDEX idx_comments_spot_created ON comments(spot_id, created_at);

-- ============================================
-- END OF SCHEMA
-- ============================================
