-- Create social tables and RLS policies for Supabase

-- COMMENTS
CREATE TABLE IF NOT EXISTS public.comments (
  id bigint generated by default as identity primary key,
  spot_id bigint not null,
  user_id uuid not null,
  content text not null,
  created_at timestamptz default now()
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS comments_read_approved ON public.comments;
CREATE POLICY comments_read_approved
  ON public.comments FOR SELECT
  USING (true);

DROP POLICY IF EXISTS comments_insert_own ON public.comments;
CREATE POLICY comments_insert_own
  ON public.comments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS comments_delete_own ON public.comments;
CREATE POLICY comments_delete_own
  ON public.comments FOR DELETE
  USING (auth.uid() = user_id);

-- RATINGS
CREATE TABLE IF NOT EXISTS public.ratings (
  id bigint generated by default as identity primary key,
  spot_id bigint not null,
  user_id uuid not null,
  score int not null check (score >= 1 and score <= 5),
  created_at timestamptz default now()
);

ALTER TABLE public.ratings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ratings_read ON public.ratings;
CREATE POLICY ratings_read
  ON public.ratings FOR SELECT
  USING (true);

DROP POLICY IF EXISTS ratings_insert_own ON public.ratings;
CREATE POLICY ratings_insert_own
  ON public.ratings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS ratings_update_own ON public.ratings;
CREATE POLICY ratings_update_own
  ON public.ratings FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- FAVORITES
CREATE TABLE IF NOT EXISTS public.favorites (
  id bigint generated by default as identity primary key,
  spot_id bigint not null,
  user_id uuid not null,
  created_at timestamptz default now(),
  unique (user_id, spot_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS favorites_read_own ON public.favorites;
CREATE POLICY favorites_read_own
  ON public.favorites FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS favorites_insert_own ON public.favorites;
CREATE POLICY favorites_insert_own
  ON public.favorites FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS favorites_delete_own ON public.favorites;
CREATE POLICY favorites_delete_own
  ON public.favorites FOR DELETE
  USING (auth.uid() = user_id);

-- REPORTS
CREATE TABLE IF NOT EXISTS public.reports (
  id bigint generated by default as identity primary key,
  spot_id bigint not null,
  user_id uuid not null,
  reason text not null,
  status text default 'pending',
  moderated_by uuid,
  moderation_note text,
  created_at timestamptz default now(),
  moderated_at timestamptz
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS reports_insert_own ON public.reports;
CREATE POLICY reports_insert_own
  ON public.reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS reports_read_mod ON public.reports;
CREATE POLICY reports_read_mod
  ON public.reports FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.user_id = auth.uid()
        AND p.role IN ('moderator','admin')
    )
  );

DROP POLICY IF EXISTS reports_update_mod ON public.reports;
CREATE POLICY reports_update_mod
  ON public.reports FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.user_id = auth.uid()
        AND p.role IN ('moderator','admin')
    )
  );
